### PR TITLE
Simplify customization of autocomplete views

### PR DESCRIPTION
**Pull request by EvaSDK**
Make it easier to select the adequate field to filter against so subclasses can properly use super() and stop having to redefine whole queryset because of this.

Hardly a big change but this annoyed me pretty much when I realized I had to write more lines than needed for a simple attribute name change.

### CODE REVIEW

**Comment by jpic** [comment]
We'll need tests and documentation, here's some background history that you might be able to use: https://github.com/yourlabs/django-autocomplete-light/issues/783

**Comment by jpic** [comment]
Hello ! Would it be possible to add just a small unit test before we release this ?

**Comment by EvaSDK** [comment]
I'd rather delay the inclusion of this. I have had a look at the history as suggested and I started work on it. Some work priorities got in the way though hence the delay.

**Comment by toudi** [comment]
damn, I am so utterly sorry that I failed to deliver this feature in half a year.. :( I just managed to find some free time today and I'll still see what can I come up with

**Comment by jpic** [comment]
@toudi don't worry about it, time is not the same, for humans and for software, time doesn't matter only <3 matters :dancer:

**Comment by jpic** [comment]
Added in #954

**Pull request closed without merging**
