### PR TITLE
Prevent rendering of empty option on multi select

### PR DESCRIPTION
**Pull request by johandc**
Fixes: Select2Multiple adds empty choice #825 for Django >1.10
See also PR #826

### CODE REVIEW

**Comment by jpic** [comment]
Nice ! Should we have a test case for this ?

**Comment by beruic** [comment]
Probably, but we (@johandc and I) are on vacation at the moment :)

**Comment by johandc** [comment]
This fix is exactly similar to the previous one that has been in the main-line for quite some time.

Did you make a test case back when you fixed this issue for Django <1.10?

With that taken into consideration i belive it is safe to pull this.

**Comment by jpic** [comment]
Thanks, this will be in next release, #953

**Pull request closed without merging**
