### PR TITLE
Update `dj111` branch to 3.2.10 release, add port of af721ca from master

### PR DESCRIPTION
**Pull request by mandarg**
Hi,

This is my first stab at a pull request for the issue mentioned in #1070. The approach here is:

- Rebase `dj111` onto tag `3.2.10` to get all the updates till 3.2.10 (since that's the last supported `dal` release for Django 1.11)
- Fix merge conflicts
- Put my fix at the tip of the (updated) `dj111` branch
- [Future, hopefully] Cut all 3.2.x releases from this branch, since someone on Django 2 will want >=3.3.x anyway

Does this approach sound correct in general? 

As for specific things – other than my fix, the only non-common commits are 8f9a5ab, 5f35557, and e45972d. I fixed merge conflicts roughly as things made sense to me, but it's probable that I made mistakes there, and would appreciate input from someone more familiar with the testing setup.

### CODE REVIEW

**Comment by jpic** [comment]
Amazing effort, i've read it and have found no malware, so, should we release this in a new package like django-autocomplete-light-dj111 ? lawl :joy:

**Comment by jpic** [comment]
Hey, did you try copying the staticfiles from Django 2.0 in like src/dal_dj111/static/admin ... ?

Then you could enable Django 1.11 support in INSTALLED_APPS or something ?

What do you think ?

Keep up the great energy you will save the days for many users :+1:

**Comment by mandarg** [comment]
So I see three possible approaches here:

Given your comment:
> should we release this in a new package like django-autocomplete-light-dj111 ? 

Let's call this **Approach A** would be to release this in a completely different package, called `django-autocomplete-light-dj111`.

Some problems with this approach that I see:
- Documentation would have to be written about this separate package for Django 1
- Versioning would be somewhat odd. What would the first version of this package be?

> Hey, did you try copying the staticfiles from Django 2.0 in like src/dal_dj111/static/admin ... ? Then you could enable Django 1.11 support in INSTALLED_APPS or something ?

I have not tried this, but the end effect would be (if I understand your query correctly), something like:

```
# DAL for Django 1
INSTALLED_APPS = [ 'dal_dj1'...
```
and
```
# DAL for Django >=2
INSTALLED_APPS = ['dal'... 
```

right? Basically the package would be the same, but you'd have different apps in `INSTALLED_APPS` for Django 1. Let's call this **Approach B**.

Again, I see the following problems with this approach
- Extra documentation needs to be written
- The concept of separate installed apps for Django 2 v/s 1 when you're using the same underlying package is somewhat confusing

In my comment above, I have suggested **Approach C** – which is, you merge this MR into branch `dj111`and simply tag commit 2409a35aa6772b459cf966388556bd05625ed81e as `3.2.11`. This gets around the problems I see in the approaches above:
- A very minor change in documentation is required (specifying that Django 1 is supported only for 3.2.x
- Versioning makes sense, and we don't have to figure out any new versioning for the - `-dj1` package

So, my view is that we should use Approach C and just tag 3.2.11 and all future 3.2 releases off the `dj111` branch. Since you have [already stated](https://github.com/yourlabs/django-autocomplete-light/issues/1058#issuecomment-427659693) that 3.3+ releases won't explicitly support Django 1, this goes very well with it – if someone asks for Django 1 compatibility, you can simply point them to the `dj111` branch and say “Accepting pull requests” :)

Thoughts?

**Comment by jpic** [comment]
LGTM

**Comment by jpic** [comment]
Fixed by 3.4.1 release

**Pull request closed without merging**
