### PR TITLE
Django 4.0 imports with fallbacks

### PR DESCRIPTION
**Pull request by blag**
This PR fixes more imports for Django 4.0+ while still retaining the old import paths to maximize reverse compatibility.

### CODE REVIEW

**Comment by whob13** [comment]
Is there a timeline for when this will be merged? I'd like to transition a project to 4.0 but will wait on this if it's coming soon.

**Comment by Mogost** [comment]
It's better to use version checking instead of feature checking. https://adamj.eu/tech/2020/01/07/feature-checking-versus-version-checking/

**Comment by blag** [comment]
> It's better to use version checking instead of feature checking. https://adamj.eu/tech/2020/01/07/feature-checking-versus-version-checking/

I would be happy to merge a PR into my branch implementing that.

**Comment by whob13** [comment]
I think @Mogost makes a valid point in his comment, but perhaps this can be merged to remain compatible with Django 4 to unblock it? Thank you for the response, @blag !

**Comment by blag** [comment]
Superseded by #1268. :tada:

**Pull request closed without merging**
