### PR TITLE
Fix RemovedInDjango20Warning for 'reverse' imports

### PR DESCRIPTION
**Pull request by luksen**
Hi,

I only did a search and replace for this but I don't see what could go wrong^(tm).

### CODE REVIEW

**Comment by jpic** [comment]
Seems like it breaks Django 1.8 support:
https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/195213265​

Note sure up to when we need to support this version, but that migth be
until the end of this year.

Meanwhile, we could have try/except ImportError :)

**Comment by luksen** [comment]
That's how other projects seem to handle it as well. I reverted the tutorial back to the old import because I think the whole try-except would be ugly there.

**Comment by jpic** [comment]
Nice ! I think the best in the docs is to have the new import though,
perhaps the old one could be left in a comment.

**Comment by luksen** [comment]
Good idea! Something like this?

**Pull request merged**
