### PR TITLE
Fix all flake8 issues in the code

### PR DESCRIPTION
**Pull request by monim67**
The `flake8` errors has been fixed. The build still will not pass on master branch as the build fails while deploying the master branch if it does not fail on `flake8` tests.

### CODE REVIEW

**Comment by monim67** [comment]
Still some flake8 issues are there which did not show up locally on my laptop, I will upload a new commit fixing those.

**Comment by monim67** [comment]
Here `flake8` command is running in Python 2.7. But there are code blocks used in the project specific to python 3 and invalid in the context of python version 2 e.g [this](https://github.com/yourlabs/django-autocomplete-light/blob/28fc4985b92ab4500770e929aad0af5a5345e257/src/dal_select2_queryset_sequence/fields.py#L15). So if we want `flake8` tests to pass without making any structural changes we need to run the test in Python 3 [here](https://github.com/yourlabs/django-autocomplete-light/blob/53aabbfbd0b676b7f600fbfc7f1daa0de030d846/tox.ini#L42). What should I do?

**Comment by monim67** [comment]
I need someone to look into this pull request. Should I alter the settings of `testenv:checkqa`?

**Comment by jpic** [comment]
First, thanks a heap for your contribution, highly appreciated !

Can you make sure tox -e checkqa passes too please ?

Thanks again, really nice !

**Comment by monim67** [comment]
I have another commit to push, that passes `tox -e checkqa` on python 3.7, it will pass on any python 3.x version but it won't pass on python 2.7 for the reasons I stated above. Base python currently in use in tox.ini is 2.7. So this command won't pass on travis test.

**Comment by jpic** [comment]
Thanks Munim, go ahead for the python upgrade

**Comment by monim67** [comment]
The branch is ready for merge now, waiting to see "build:passing" badge again :)

**Comment by monim67** [comment]
The tests passed, but the deploy script encountered some error. Now it's in your hand mate.

**Comment by jpic** [comment]
Deployment was on OpenShift 2 which is dead. We have a new infra (gitlab+k8s which you might have seen video demo of on the blog) but I don't have time to migrate DAL there. However, we're posting an offer maybe someone will take it who knows 
2018-09-19-192938_958x318_scrot

Otherwise, it'll have to wait until i have time, maybe next year :joy:

**Pull request merged**
