### PR TITLE
Adding dark mode support

### LINKED ISSUE #1245: Dark mode support
Django 3.2 introduces dark mode in its admin website. DAL looks very poorly and need to take the same (or similar) styles as django autocomplete.

### PR DESCRIPTION
**Pull request by trumpet2012**
This fixes #1245 where the select2 fields don't honor the Django dark mode theme.

The fix requires using the CSS variables defined by the Django admin. These variables get used for both dark mode and light mode. For older Django versions < 3.2 before these variables were added, a fallback value is provided that matches the default styling that select2 was using.

Below you can see the comparison between the different fields and their states before and after these changes are applied.

<details><summary>Dark Mode Comparison</summary>
<p>

<details><summary>List comparison</summary>
<p>

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

</p>
</details>

<details><summary>Table comparison</summary>
<p>

| Field Type | Field State | Before | After |
| --- | --- | --- | --- |
| Multiple Choice | Empty/Inactive | image | image |
| Multiple Choice | Empty and dropdown open | image | image |
| Multiple Choice | 1 selected | image | image |
| Multiple Choice | 1 selected and dropdown open | image | image |
| Multiple Choice | 1 selected and searching | image | image |
| Single Choice | Empty/Inactive | image | image|
| Single Choice | Empty and dropdown open | image | image |
| Single Choice | Choice selected | image | image |
| Single Choice | Choice selected and dropdown open | image | image |
| Single Choice | 1 selected and searching | image | image |

</p>
</details>

</p>
</details>

<details><summary>Light Mode Comparison</summary>
<p>

<details><summary>List comparison</summary>
<p>

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image 

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

#### Before
image

#### After
image

</p>
</details>

<details><summary>Table view</summary>
<p>

| Field Type | Field State | Before | After |
| --- | --- | --- | --- |
| Multiple Choice | Empty/Inactive | image  | image  |
| Multiple Choice | Empty and dropdown open | image | image |
| Multiple Choice | 1 selected | image  | image |
| Multiple Choice | 1 selected and dropdown open | image  | image |
| Multiple Choice | 1 selected and searching | image | image |
| Single Choice | Empty/Inactive | image | image |
| Single Choice | Empty and dropdown open | image | image |
| Single Choice | Choice selected | image | image |
| Single Choice | Choice selected and dropdown open | image | image |
| Single Choice | 1 selected and searching | image | image |

</p>
</details>

</p>
</details>

### CODE REVIEW

**Comment by jpic** [comment]
Great contributions :tophat:

**Comment by daweedm** [comment]
Which version of DAL should we use to have this PR included ? Currently the latest (3.9.4) has still this issue

**Comment by ram495** [comment]
Hello @trumpet2012 Can you please let me know which version of dal has this support?

**Comment by trumpet2012** [comment]
@ram495 @daweedm It should be in version `3.9.7` and later

**Pull request merged**
