### PR TITLE
Made Select2ListView return case insensitive results by default

### PR DESCRIPTION
**Pull request by DSynergy**
-Made select2ListView return a case insensitive match by default
to match the select2QueryView
-Added a kwarg to toggle case sensitivity in select2ListView get()

### CODE REVIEW

**Comment by jpic** [comment]
I think we should better drop case_insensitive and just leave the insensitive search.

However, we need to add a regression test.

**Comment by DSynergy** [comment]
Sure I can drop the kwarg, that is no problem. I actually work at eGauge systems with David and Joshua, the original contributors for the list select, so just patching their work.

What sort of regression test would you want?

Should the Travis-cl be passing currently? Looks like it is missing a package 'white-noise'?

**Comment by jpic** [comment]
Just a test for your patch, feel free to add more if you're into this kind of stuff :dancer:

**Comment by DSynergy** [comment]
Okay, I have updated the commit and added a thorough test for both my change and the Select2ListView in general

**Comment by jpic** [comment]
Really awesome, thanks !!!

**Comment by DSynergy** [comment]
Sounds good. Glad I could help

**Pull request merged**
