### PR TITLE
case insensitive Select2ListView

### PR DESCRIPTION
**Pull request by jsurloppe**
Hi,

This PR allow to do case insensitive research in a Select2ListView.

### CODE REVIEW

**Comment by jpic** [comment]
Does case sensitive search really make sufficient sense to keep it at all ?

**Comment by jsurloppe** [comment]
I don't need it myself, i  have  done it like this for ensuring backward compatibility.

**Comment by jpic** [comment]
Ok let's just get rid of case sensitive search and only do case insensitive instead would that work for you then ?

**Comment by DSynergy** [comment]
Funny...I just did this in #821

**Comment by jsurloppe** [comment]
LGTM, i suggest merging #821, closing #822 and i'll modify #823 according.

**Comment by jpic** [comment]
OMG I'm so tired, I thought it was the same PR ... We need to recruit core devs, I can barely follow up.

**Pull request closed without merging**
