### PR TITLE
Fixes a bug where ampersand cannot be typed on Chrome/Mac

### PR DESCRIPTION
**Pull request by aidanlister**
Fixes issue #294, fix by @yliharma

### CODE REVIEW

**Comment by blueyed** [comment]
Please test if https://github.com/yourlabs/django-autocomplete-light/pull/398 also fixes this.

**Comment by yliharma** [comment]
Nope, #398 broke the ampersand again :(

**Comment by jpic** [comment]
Is it fixed in 2.1.0rc2 ?

Thanks for your feedback B)

**Comment by yliharma** [comment]
It works...but I'm not sure which version I'm using.
I upgraded the package running `pip install -U -e git+https://github.com/yourlabs/django-autocomplete-light.git#egg=autocomplete_light` in my virtualenv and in the output there was `django-autocomplete-light 2.1.0rc2 is already the active version in easy-install.pth` but if I open a python shell and import the module, the output of `autocomplete_light.VERSION` is `(1, 6, 10, 'final', 0)`...

**Comment by jpic** [comment]
Lol nice one, this is because of django 1.9 support xD

https://github.com/yourlabs/django-autocomplete-light/blob/76a617b4aaffd36ae61c29748fe480cccdc9cffb/autocomplete_light/__init__.py

What you're seeing here is Django's version !

Gotta fix this

**Comment by aidanlister** [comment]
pip freeze to see your version info

**Comment by yliharma** [comment]
Aidan it's not easy to understand...the output is  `-e git+https://github.com/yourlabs/django-autocomplete-light.git@76a617b4aaffd36ae61c29748fe480cccdc9cffb#egg=django_autocomplete_light-master` where probably the portion between @ and # is the changeset number...but then I would have to look for this commit: boring!!! I can tell you that it's not the last commit.

**Comment by jpic** [comment]
Ok cd in yourenv/src/django_autocomplete_light and do git pull origin master.

PEP 396 is implemented now so autocomplete_light.__version__ should be available.

**Comment by yliharma** [comment]
Perfect! Thank you :+1:

**Pull request merged**
