### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
It fails on Django 1.4, but I don't know why.. https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/52020856.

**Comment by blueyed** [comment]
I cannot reproduce it locally using `tox -e py27-django14 -- autocomplete_light.DependentAutocompleteEmptyFormTestCase`, after merging it with the `improved-toxini` branch/PR.

**Comment by blueyed** [comment]
Closing, everything cherry-picked.

**Comment by jpic** [comment]
From 1h30 to 14 minutes I'm high on the performance boost - which is the kind of problem I like to have.

Keep up the great work

Rock'on B)

**Pull request closed without merging**
