### PR TITLE
Replacing clear-fix with newer version, as the older version breaks the ...

### PR DESCRIPTION
**Pull request by sbaum**
...display of inline forms in Django 1.7.
See discussion: https://github.com/yourlabs/django-autocomplete-light/pull/334#issuecomment-75745309

### CODE REVIEW

**Comment by blueyed** [comment]
I'll merge / handle this and add a test for it.

**Comment by jpic** [comment]
Thanks a heap i can barely keep up with updates this week
I wonder how you intend to test it though, it's purely graphical isn't it?

**Comment by blueyed** [comment]
@jpic 
I am looking for `width=0` in a LiveServerTestCase: https://github.com/blueyed/django-autocomplete-light/commit/aaeeeba9a0546c6f8f369a45e3bef3268d56ff8d

**Comment by jpic** [comment]
Awesome keep up the great work

**Pull request closed without merging**
