### PR TITLE
Exclude src/dal/test instead of src/dal/tests to fix flake8 failure

### PR DESCRIPTION
**Pull request by thauk-copperleaf**

### CODE REVIEW

**Comment by thauk-copperleaf** [comment]
@jpic This should fix the checkqa build (flake8), at least

**Comment by jpic** [comment]
I don't understand, what does this fix exactly ?

**Comment by thauk-copperleaf** [comment]
https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/196763240

```
...
checkqa runtests: commands[0] | flake8 --show-source --max-complexity=7 --ignore=D203 --exclude src/dal/autocomplete.py,tests src
src/dal/test/stories.py:48:1: C901 'BaseStory.find_option' is too complex (8)
    def find_option(self, text, click=False):
^
ERROR: InvocationError: '/home/travis/build/yourlabs/django-autocomplete-light/.tox/checkqa/bin/flake8 --show-source --max-complexity=7 --ignore=D203 --exclude src/dal/autocomplete.py,tests src'
...
```

It seemed to me that you were attempting to exclude tests from flake8. Am I incorrect?

**Comment by jpic** [comment]
Right, it would be better to decomplexify that function but i'm not sure if it's really possible.

**Comment by jpic** [comment]
> It seemed to me that you were attempting to exclude tests from flake8. Am I incorrect?

Nope, all code should be covered by flake8, just with different set of options.

**Pull request closed without merging**
