### PR TITLE
Attempt to fix #1219

### LINKED ISSUE #1219: Using data-html has no effect when rendering new option
1. Set `data-html=true` for your select2 widget
2. Return HTML in AJAX response

**Problem**: HTML is not interpreted but displayed as text:

This seem to be related to https://github.com/yourlabs/django-autocomplete-light/issues/1171. Looks like its fix was not quite correct.
As I understand, the problem happens because of `$('<span>').text(...)` call here - https://github.com/yourlabs/django-autocomplete-light/blob/3.8.1/src/dal_select2/static/autocomplete_light/select2.js#L28 
If `data-html` is set we want to do `$(<span>).html`, not `$(<span>).text()`

### PR DESCRIPTION
**Pull request by eprikazc**
Attempt to fix #1219

### CODE REVIEW

**Comment by jpic** [comment]
Can't we just replace the .text by a .html call ? Can you check if that works for both case ?

**Comment by eprikazc** [comment]
@jpic - if we just replace `text()` with `.html()`, then text in new option will **always** be interpreted as HTML, even when `data-html` attribute is not set. I assume this is not what we want?

**Comment by jpic** [comment]
I see, that might not be very safe after all, because Django allows all
unsafe characters by default in CharFields, so an injection is easy if one
just does something like `'<b>' + obj.name + '</b>`, the injection here is
obvious. This is because Django refuses to apply the OWASP security policy
that is: secure the input, not the output!

It's better to leave it this way and make this insecurity an opt-in, do you
think we also need tests or documentation?

**Comment by eprikazc** [comment]
This PR does not add any new behavior, it is rather a bugfix, so no new docs are needed.. I think existing [documentation](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#displaying-results-using-custom-html) already covers rendering of custom html quite well.
RE tests - yeah, probably adding a test or two might be helpful to prevent regressions in future. I can try to prepare them. Though, I haven't found in documentation any instructions/links on how we're supposed to run/write tests. Any hints?

**Pull request merged**
