### PR TITLE
Ensure language support

### LINKED ISSUE #782: The language file for "./i18n/en-us" could not be automatically loaded. A fallback will be used instead
On a clean install, Django 1.10, I get the following message:

`The language file for "./i18n/en-us" could not be automatically loaded. A fallback will be used instead`

I see that in the src and dist folders the translation files don´t have the sublanguage suffixes.

What´s the best practice here?

### PR DESCRIPTION
**Pull request by wgordon17**
Closes #782

### CODE REVIEW

**Comment by wgordon17** [comment]
@jpic Care to review?

**Comment by jpic** [comment]
Looks great, maybe you want to cover get_i18n_name with a few tests, ie. fr-US, fr-FR and whatnot, just to prevent further contributors from breaking your stuff, otherwise it's good for merge :+1:

Keep up the gr8 work :1st_place_medal:

**Comment by wgordon17** [comment]
@jpic Good call on the tests...found one issue which has been resolved. Did I put my tests in the right place? I fixed the `FAIL`s caused by my change, but there were a number of `ERROR`s reported when running `test_project/manage.py test`.

**Comment by jpic** [comment]
Looks good to me, good job fixing those tests ! so, any last minute objection or can we merge now ?

**Comment by wgordon17** [comment]
I'm good with merging...threw my last second fix in to get a green Travis 👍

**Comment by wgordon17** [comment]
Thanks for your help 😄

**Comment by jpic** [comment]
Thank YOU for your awesome contribution, from what I've read you've made history for many users :medal_sports: 

As contributor your are invited to spend some time in our hackerspace in the country side south west of France, where they make fine cognac, pineau, wine and cheese.

Have a fantastic weekend :+1:

**Comment by coredumperror** [comment]
Could a new release be made that has this fix, please? It appears that the most recent release was in April.

**Comment by jpic** [comment]
Released in 3.3.5

**Comment by coredumperror** [comment]
Thank you!

**Pull request merged**
