### PR TITLE
Fix Django 1.9 import error

### PR DESCRIPTION
**Pull request by arnists**
This is really just a test to see if CI breaks (see closed PR https://github.com/yourlabs/django-autocomplete-light/pull/501).

### CODE REVIEW

**Comment by blueyed** [comment]
Yeah, what have you expected? :)

I've now merged #502 and restarted the build.

**Comment by blueyed** [comment]
I think it would be better to re-open #501 and close this one here.
Re-opening it should also trigger a rebuild then.

**Comment by blueyed** [comment]
Oh, but you would need to re-push or undelete your branch over there.

**Comment by arnists** [comment]
This is the clean branch with no problems, one commit.  Do you need me to do anything?  Travis is yellow (I'm new to CI, don't know the proper procedure).

**Comment by blueyed** [comment]
I've meant that the previous PR would be better because of the discussion etc.
Not reviewing anything currently, just wanted to get CI going again.
Yellow means that it's in progress still.

**Comment by jpic** [comment]
Pretty cool, thanks !

**Pull request merged**
