### PR TITLE
[WIP] Restore compatibility with querysetsequence==0.9

### PR DESCRIPTION
**Pull request by optiz0r**
This commit contains a partial fix restoring compatibility
with querysetsequence==0.9 by dropping use of a private api
in favour of a public one.

Instead of using the content-type id and object-id as the value
for select options, instead the queryset index and object id are
used. The `QuerySetSequence` maintains an ordered list of the
`QuerySet` objects it is composed of, and the index can be used
retrospectively to retrieve the model given the index and pk.

See also: https://github.com/percipient/django-querysetsequence/issues/21#issuecomment-432649275
Partial fix for #1050

### CODE REVIEW

**Comment by jpic** [comment]
Thank you for your contribution @optiz0r 

However, is it possible to fix the `tox -e checkqa` job ? Note that there were 4 failures that I just fixed in master so you might want to rebase.

**Comment by optiz0r** [comment]
Found some issues with this in testing; not good to merge yet. (I was really abusing the PR to run the tests as they weren't running properly locally).

**Comment by optiz0r** [comment]
Approach flawed, abandoning this PR.

**Comment by jpic** [comment]
Why that ?

**Comment by optiz0r** [comment]
commentary in #1050

**Comment by jpic** [comment]
Harsh !
​
All my deepest respect for going through with your attempt @optiz0r 

I guess we're going to need a "get first queryset matching that content type" kind of method upstream in dqss after all

**Comment by optiz0r** [comment]
Indeed. I updated the ticket on the QSS side too. Bit awkward having this conversation trailed across three separate threads, which is partly why I closed this one down.

**Comment by jpic** [comment]
Sorry about that, but it's on my backlog to start being active on dal soon
and clean up some of the mess / make a release taking in account all recent
feedback, perhaps even migrating CI to gitlab so that we have use resources
from our CI server and have much more stable results from selenium ...I
mean: i know it's become messy and plan to do something about it ;)

**Pull request closed without merging**
