### PR TITLE
Fixed JS autocomplete initializer (#819)

### PR DESCRIPTION
**Pull request by apinsard**
Call initialize() manually once 'autocompleteLightInitialize' event
listener is set on select2.js.

This allows the initializer to be called even when the DOM is ready
before select2.js was loaded.

Also replaced 'element = $(this).get(0)' by 'element = this' which
should be equivalent in this scope.

### CODE REVIEW

**Comment by jpic** [comment]
Thanks !

Could you rebase this on master so I can check if this broke any tests (which are now passing).

In the best case, i'll be able to merge and release this this week end.

**Comment by jpic** [comment]
Hello @apinsard !

Tests are passing on master, could you rebase please ?

When this is rebased and doesn't break tests I'd like to release this !

**Comment by apinsard** [comment]
@jpic Done

**Comment by jpic** [comment]
It didn't pass any integration test on Travis-ci, does it pass for you ?

Merci Antoine <3

**Comment by apinsard** [comment]
Indeed... Yet I don't get what could make tests fail as I haven't changed any python file

**Comment by jpic** [comment]
Apparently no selenium test is passing anymore.

**Comment by jpic** [comment]
I still have hope in this !

Salutations from POITOU CHARENTE <3

**Pull request merged**
