### PR TITLE
simple model autocomplete - initial draft

### PR DESCRIPTION
**Pull request by toudi**
This is an initial draft for what I call 'simple autocomplete for models'.

@jpic I would like to deeply and sincerely apologise for this insane delay. Could you please take a look at this initial draft and guide me how it should be secured / enhanced ?

Dear friend developer @EvaSDK from PR #815 - could you take a look at this as well ?

Here's a sample usage:

```
#urls.py
from django.conf.urls import url
from dal_select2.views import Select2GenericModelQuerySetView
from models import Parent # this is my model class, it contains 2 fields - first_name, last_name

urlpatterns = [
    url(r'^$', views.index),
    url(
        r'^ac',
        Select2GenericModelQuerySetView.as_view(
            model=Parent,
            search_fields=('first_name', 'last_name'),
        ),
        name='parent-ac',
    )
]

#views.py
from django.shortcuts import render
from forms import Search

# Create your views here.
def index(req):
    form = Search()

    return render(
        req,
        'foo/test.html', {
            'form': form
        }
    )

#forms.py
from django import forms
from models import Parent
from dal_select2.widgets import ModelSelect2


class Search(forms.Form):
    parent = forms.ModelChoiceField(
        queryset=Parent.objects.all(),
        widget=ModelSelect2(url='parent-ac')
    )

    class Meta:
        exclude = []

```

p.s. I tried to implement this in v2 branch as well, but I failed to see where are the views for select2 :/

### CODE REVIEW

**Comment by jpic** [comment]
Don't worry about the v2 branch.

I'm all for such an improvement, however, isn't there some library already encapsulating such logic we could depend on ? 

Ie. https://github.com/gregplaysguitar/django-simple-search

Otherwise, shouldn't we make such a package ?

I mean that I'd like to reuse that in a search form or something, I think it makes sense to have this feature with dal, but I'm not convinced that the actual code belongs to dal itself. 

What do you think ?

**Comment by toudi** [comment]
Hmm I'm not so sure whether it would be justifiable to depend on 3rd party library. If you look at the changes I made, you'd see that the changes minus the documentation is something like 15 lines of code. Actually, my code is actually a very thin inheritance of the View already provided by dal - it only makes advantage of different fields than `name`.

I would also like to point out that it is not my goal to extend and extend this class even more, because it would most certainly create the complex config structure in `urls.py`. In my opinion, if one wants something other than this pure simple autocomplete, based on specified fields, this is a good place to start implementing custom views with get_queryset

I have no idea whether django-simple-search provides this feature - I kind of always used dal, and my only papercut was that I had to repeat and repeat these views with get_queryset simply because I wanted to autocomplete by different fields

About the reusing in search form - I don't think I  understand your question. The example which I have added shows the Search form, right ? Or are you referring to some generic Search Form ?

**Comment by jpic** [comment]
Yes of course this is simple enough but in v2 this grew in a pretty empiric way.

So perhaps you might prefer to just port that code in v3 ? It's got a lot of good features:

https://github.com/yourlabs/django-autocomplete-light/blob/v2/autocomplete_light/autocomplete/model.py

**Comment by toudi** [comment]
of course I can try to :D I just hope that I won't be delayed as much as I was before creating this PR.. otherwise by the time I came up with a PR there will already be v4 of dal :D

**Comment by toudi** [comment]
actually, wait a second.. I can see in my comment that I failed to provide a PR for v2 branch, therefore this change should already be compatible with v3.. or ?

**Comment by jpic** [comment]
Yeah sorry about that, you were already on v3 yes ;)

v2 was bloat over v1, v3 is v2 without the bloat ;)

**Comment by toudi** [comment]
hmm so I don't quite understand your comment. Does it mean that this PR is no longer necesary because current v3 already provides such features?

**Comment by jpic** [comment]
v3 doesn't provide such feature, i thought someone would extract that from v2 and release it in a separate app, because you know, it can be useful for any generic list view, not specifically to DAL ;)

about the pr yes coverage would be welcome to help with future python or django version upgrades, coverage drastically reduce maintenance cost over years ;)

also, perhaps we could already use the same search_fields as in v2 ? those were user contributed, they are going to contribute it again anyway if we don't port it i can see them coming haha

**Comment by jpic** [comment]
Do you we should use SearchForm from django-betterforms ?

https://github.com/jpic/django-betterforms/blob/master/betterforms/changelist.py#L66

Then, we could contribute search_fields improvements there.

**Comment by jpic** [comment]
My last comment turned completely wrong as django-betterforms has died since, but 053554937475e1a34a5e48de5bf6d66c90e9de45 pastes the search_fields feature from django.contrib.admin and no one has been complaining so far :joy:

:tophat:

**Pull request closed without merging**
