### PR TITLE
tests reqs: pin pytest-django==2.9.1

### PR DESCRIPTION
**Pull request by blueyed**
Could be unpinned again, but it makes sense to not break tests because
of that in the future.

If you agree, other deps could be pinned also?!

### CODE REVIEW

**Comment by jpic** [comment]
It would definitely help to pin versions ! Thanks @blueyed

**Comment by blueyed** [comment]
You're very welcome!
See https://github.com/pytest-dev/pytest-django/issues/282 for the new issue with 2.9.1.

**Comment by jpic** [comment]
Could you try to rebase on master please ? I think tests will pass then.

**Comment by blueyed** [comment]
Nope, still failing.

**Comment by jpic** [comment]
I don't think we need this anymore, do we ?

**Comment by blueyed** [comment]
> I don't think we need this anymore, do we ?

What do you mean?  This PR is about using the latest pytest-django again.

I've re-pushed it rebased on master.

**Comment by blueyed** [comment]
Seems to be still this issue: https://github.com/pytest-dev/pytest-django/issues/282

**Pull request closed without merging**
