### PR TITLE
#476 - Documentation is a mess 

### PR DESCRIPTION
**Pull request by Visgean**
Improving titles and toc indexes for issue #476

### CODE REVIEW

**Comment by jpic** [comment]
Nice, could you rebase and make only one commit maybe ?

It's a bit weird to have maxdepth changes in commit 5388db1 in addition to the new titles.

**Comment by Visgean** [comment]
Well now its just one commit :) ... well except for the merge..

**Comment by jpic** [comment]
Ouch, how did you did this ? :)

Did you try `git rebase -i origin/master` ?

**Comment by Visgean** [comment]
I did 
 git rebase -i HEAD~2

But at this point I have no idea what I am doing :D

**Comment by jpic** [comment]
Change all "pick" to "fixup" except for the one with "Hiding docs sections
from main navigation ".

**Comment by Visgean** [comment]
There you go.

**Comment by jpic** [comment]
Thanks !!

**Comment by Visgean** [comment]
Strangely docs build failed... https://readthedocs.org/builds/django-autocomplete-light/3256568/ :(

**Comment by jpic** [comment]
I asked in `#readthedocs` irc channel

**Comment by blueyed** [comment]
@Visgean 
Thanks for addressing this!

**Comment by jpic** [comment]
> `16:21 < nedbat> is_null: this seems to be happening randomly to people.  My projects get it too.`

**Pull request merged**
