### PR TITLE
Django 4.0 test

### PR DESCRIPTION
**Pull request by jpic**
Fix Django 4 support

Do not deploy in 3.9 as this will probably break some Django 2.x support and even more whatever still works on Django 1.x

### CODE REVIEW

**Comment by blag** [comment]
#1279 introduces Django 4.0 imports with fallbacks to preserve reverse compatibility with older Django versions. However, that PR doesn't update `test_project/requirements.txt` or `tox.ini`.

@jpic Can the changes to those files be split out into a separate PR, or are they required for Django 4.0 support?

**Comment by spapas** [comment]
Hello @jpic I'd like to confirm that version `3.9.0rc5` works great with django 4.0.1. I'm looking forward to this release :-)

Kind regards,
Serafeim

**Comment by jpic** [comment]
Sure thing! 3.9.0 released

Don't forget to check out my new favorite feature :joy:

https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#automation-with-djhacker

Njoy

**Comment by spapas** [comment]
Hello @jpic it seems that the 3.9.0 can't be found on pip: https://pypi.org/project/django-autocomplete-light/#history 

any idea ? 

Thank you!

**Comment by jpic** [comment]
Yes, I removed it temporarily because it breaks whitenoise apparently.

**Pull request merged**
