### PR TITLE
Prevent rendering of empty option on multi select

### PR DESCRIPTION
**Pull request by beruic**
Fixing issue #825

### CODE REVIEW

**Comment by jpic** [comment]
Looks really good, I hope to fix tests during djangocon so we can merge this and other prs that have been waiting.

**Comment by jpic** [comment]
I mean, it'll be in next release, so don't worry if you're relying on your fork for now :)

**Comment by beruic** [comment]
Awesome. I think I can postpone out next release a few days, so as long as you make a new release here on GitHub too, I'll be notified automatically :)

**Comment by jpic** [comment]
I think there's a bit of a misunderstanding here, are you sure you're able to use your fork with your patch or do you have time to fix the tests right now to unblock the release ? I thought you wanted to postpone your own release based on my volunteer time, this wouldn't be very wise would it :P

**Comment by jpic** [comment]
Seems like we're going to see the tests pass on some django versions (like before) after #827, could you rebase your PR to see if it changes something ? Thanks

**Comment by beruic** [comment]
Sorry for the slow response. I got busy and had to monkey patch it to get on with our release. Should I just rebase onto `fix_tests`?

**Comment by beruic** [comment]
And, no I am not sure I am able to use my fork, but it seems to work fine when patching version 3.2.1. If you are too busy, don't worry, I have a(n ugly) fix for now. I would love to work more on dal (especially the documentation), but unfortunately we are pressured on time for the next few months.

**Comment by jpic** [comment]
Is it possible to rebase this on the master ?

I'd like to merge this and release it :)

**Comment by beruic** [comment]
I'll do it Monday first thing ☺️

**Comment by beruic** [comment]
Arh! Sorry. I'm on vacation and off the grid next week. I will see when I can fix it.

**Comment by jpic** [comment]
Ok, we'll probably issue another release with that then.

**Comment by beruic** [comment]
Rebase done

**Comment by jpic** [comment]
I didn't expect all tests to pass, but well played !

I can get started on releasing that, would you like to code a small and basic unit test meanwhile ?

**Comment by beruic** [comment]
Since it passed, there may be cases not covered by the tests.
Sorry, I don't have time to do much more than fix the bugs that obstruct my current work. Right now we are a bit pressured on our releases, and sparetime is sparse after becoming a father.
I will however keep fixing things if I can justify it for our product :)

**Comment by jpic** [comment]
It looks like we could adapt an existing test for this particular purpose, and it doesn't even have to be a functional test, a unit test would be fine.

**Comment by jpic** [comment]
Hi again ! Another user reported a problem with this, would you like to take a look ?

https://github.com/yourlabs/django-autocomplete-light/issues/834#issuecomment-294871227

Thanks !

**Comment by beruic** [comment]
@jpic Just to clear up: Wasn't this ont supposed to be reverted due to #834 and then reapplied again when the next version of Django was released?
I just noticed that it seems like this never happened, and now there is a new Django version, so we are all good?

**Pull request merged**
