### PR TITLE
Use django-1.7 apps registry.

### PR DESCRIPTION
**Pull request by g1itch**
To deal with django-1.7 `AppConf`s in `settings.INSTALLED_APPS`. Maybe it's a part of the #247.

### CODE REVIEW

**Comment by blueyed** [comment]
Just for reference: this was never added to v2, but seems to be addressed there differently via 5b1ed105 (Fix #347 Django 1.7 AppConfig support).

**Comment by jpic** [comment]
Correct !

**Comment by blueyed** [comment]
@jpic 
Please elaborate.. what is correct?
I have cherry-picked this in a local branch already and could provide a PR - but I am not sure what you mean.

**Comment by blueyed** [comment]
I see. You've replied to my comment before I've added the 2nd paragraph.
All fine then.

**Pull request merged**
