### PR TITLE
HackHands service does not exist anymore

### PR DESCRIPTION
**Pull request by morenoh149**

### CODE REVIEW

**Comment by jpic** [comment]
Damn, I made some really nice encounters with hackhands back in the days, I remember having so much fun coaching nice people into Django !

Well, you have my personal email in git so, feel free to contact me for private code support.

Otherwise, post your question on stackoverflow or even github issues and we'll try to answer, try to catch me on #yourlabs or #django IRC channels on freenode and also there's the mailing list.

**Comment by morenoh149** [comment]
@jpic posted at so https://stackoverflow.com/questions/64684058/how-to-createtag-in-django-autocomplete-light

**Comment by morenoh149** [comment]
@jpic what is your email? I don't see it.

**Comment by jpic** [comment]
Thank you for isolating the problem in your test project, but I thought registerFunction was not working ?

The console log baz displays fine for me:

2020-11-06-213054_908x555_scrot

So, it seems you are able to pass arguments to select2 ...

And I'm not really sure what the problem is

**Comment by jpic** [comment]
My email is `'@'.join(reversed('yourlabs.org@jpic'.split('@')))`

Would be interesting to see your project with google hangouts or something like that.

**Pull request merged**
