### PR TITLE
Use namespaced jQuery in `get_forwards`

### LINKED ISSUE #792: "getFormPrefix is not a function" when using forward.Const
Hi!

I'm using this fantastic library, but then I run into a problem.
Here is a form that I use in a inline tab:

```python
class ComponentImageForm(forms.models.ModelForm):

    class Meta:
        widgets = {
            'image': autocomplete.ModelSelect2(
                url='image_autocomplete',
                attrs={
                    'data-html': 'true'
                }
            )
        }
```

It works as expected.
I need to search only for product images, and this is a hard coded key on my image model.
So, adding forward to the mix:

```python
class ComponentImageForm(forms.models.ModelForm):

    class Meta:
        widgets = {
            'image': autocomplete.ModelSelect2(
                url='image_autocomplete',
                forward=(
                    forward.Const('product', 'image_application'),
                ),
                attrs={
                    'data-html': 'true'
                }
            )
        }
```

That gives me a "getFormPrefix() is not a function" error.

What I'm doing wrong?

Thanks!

### PR DESCRIPTION
**Pull request by ryan-copperleaf**
The function `get_forwards` was defined without the usual IIFE aliasing `yl.jQuery` to `$`. Since it wasn’t used anywhere else, this also moves it inside the Select2 script to avoid defining the function globally.

Should fix #792 (#806).

### CODE REVIEW

**Comment by ryan-copperleaf** [comment]
(Linting is failing because of https://gitlab.com/pycqa/flake8-docstrings/merge_requests/7.)

**Comment by jpic** [comment]
I got a good feeling about this, let's merge it and we can still revert / work it out if @gagarski (original author of this script) finds any objection.

**Comment by gagarski** [comment]
It is not used outside select2.js but actually this code could be used for other autocomplete widgets. For now, I think we can move it back and/or refactor it when there will be any.

**Comment by ryan-copperleaf** [comment]
Thanks, everyone!

**Pull request merged**
